# Data Preprocessing

## simple imput

### 예제1

In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

x = [[7,2,3],[4, np.nan, 6],[10,5,9]]
x

[[7, 2, 3], [4, nan, 6], [10, 5, 9]]

In [2]:
# 예제 1
imp_mean = SimpleImputer(missing_values = np.nan, strategy='mean')
imp_mean.fit(x)
imp_mean.transform(x)

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  3.5,  6. ],
       [10. ,  5. ,  9. ]])

-------------------
연습

In [3]:
imp_mean = SimpleImputer(missing_values = np.nan, strategy='mean')
imp_mean.fit(x)

'''
simpleImputer() 로 fitting됨
'''

SimpleImputer()

In [4]:
imp_mean.transform(x)

'''
nan값이 mean으로 채워짐 (strategy = 'mean')
mean 계산은 열기준!
'''

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  3.5,  6. ],
       [10. ,  5. ,  9. ]])

----------------------

### 예제 2

In [16]:
# 예제 2
new_data = [[np.nan, 2, 3],[4, np.nan, 6], [10, np.nan, 9]]
new_data

[[nan, 2, 3], [4, nan, 6], [10, nan, 9]]

In [10]:
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imp_mean.fit(new_data)
imp_mean.transform(new_data)

array([[ 7.,  2.,  3.],
       [ 4.,  2.,  6.],
       [10.,  2.,  9.]])

------------------
연습

In [19]:
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imp_mean.fit(new_data)


# simpleImputer() 로 fitting됨

SimpleImputer()

In [20]:
imp_mean.transform(new_data)


# nan값이 mean으로 채워짐 (strategy = 'mean')
# mean 계산은 열기준!

array([[ 7.,  2.,  3.],
       [ 4.,  2.,  6.],
       [10.,  2.,  9.]])

----------------

## 실데이터 적용하기

### 1) 데이터 로드

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
# data loading

path = 'DataPreprocess.csv'
df = pd.read_csv(path)
df.head()

'Country' 'Age' 'Salary' 'Purchased'
0   'France'  44.0  72000.0        'No'
1    'Spain'  27.0  48000.0       'Yes'
2  'Germany'  30.0  54000.0       'No' 
3    'Spain'  38.0  61000.0        'No'
4  'Germany'  40.0      nan       'Yes'

### 2) 데이터 분할 (독립변수 | 반응변수_yes/no)

In [32]:
# 데이터와 레이블 나누기 - 종속변수(반응변수)와 독립변수(설명변수) 나누기
x = df.values[:,:-1]  # 데이터
y = df.values[:,-1]   # 레이블(정답)
x, y

(array([["'France'", '44.0', '72000.0'],
        ["'Spain'", '27.0', '48000.0'],
        ["'Germany'", '30.0', '54000.0'],
        ["'Spain'", '38.0', '61000.0'],
        ["'Germany'", '40.0', ' nan'],
        ["'France'", '35.0', '58000.0'],
        ["'Spain'", ' nan', ' 52000.0'],
        ["'France'", '48.0', '79000.0'],
        ["'Germany'", '50.0', '83000.0'],
        ["'France'", '37.0', '67000.0']], dtype=object),
 array([" 'No'", " 'Yes'", "'No' ", " 'No'", " 'Yes'", " 'Yes'", " 'No'",
        " 'Yes'", " 'No'", " 'Yes'"], dtype=object))

### 3) 결손 데이터 처리

In [42]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(strategy='mean')  # nan >> mean 평균값으로 대치 (단순대입법)
imp_mean = imp_mean.fit(x[:,1:3])  # 모델 fitting
x[:,1:3] = imp_mean.transform(x[:,1:3]) # scailing한 값으로 대체
x

# nan >> mean값으로 대치

array([["'France'", 44.0, 72000.0],
       ["'Spain'", 27.0, 48000.0],
       ["'Germany'", 30.0, 54000.0],
       ["'Spain'", 38.0, 61000.0],
       ["'Germany'", 40.0, 63777.77777777778],
       ["'France'", 35.0, 58000.0],
       ["'Spain'", 38.77777777777778, 52000.0],
       ["'France'", 48.0, 79000.0],
       ["'Germany'", 50.0, 83000.0],
       ["'France'", 37.0, 67000.0]], dtype=object)

------------------
연습

In [25]:
df.shape

(10, 4)

In [26]:
# 데이터 분할 (독립변수 / 반응변수_yes/no)
df.values

array([["'France'", '44.0', '72000.0', " 'No'"],
       ["'Spain'", '27.0', '48000.0', " 'Yes'"],
       ["'Germany'", '30.0', '54000.0', "'No' "],
       ["'Spain'", '38.0', '61000.0', " 'No'"],
       ["'Germany'", '40.0', ' nan', " 'Yes'"],
       ["'France'", '35.0', '58000.0', " 'Yes'"],
       ["'Spain'", ' nan', ' 52000.0', " 'No'"],
       ["'France'", '48.0', '79000.0', " 'Yes'"],
       ["'Germany'", '50.0', '83000.0', " 'No'"],
       ["'France'", '37.0', '67000.0', " 'Yes'"]], dtype=object)

In [27]:
df.values[:,:-1]

# 독립변수
# -1행 제외하고 1~3행

array([["'France'", '44.0', '72000.0'],
       ["'Spain'", '27.0', '48000.0'],
       ["'Germany'", '30.0', '54000.0'],
       ["'Spain'", '38.0', '61000.0'],
       ["'Germany'", '40.0', ' nan'],
       ["'France'", '35.0', '58000.0'],
       ["'Spain'", ' nan', ' 52000.0'],
       ["'France'", '48.0', '79000.0'],
       ["'Germany'", '50.0', '83000.0'],
       ["'France'", '37.0', '67000.0']], dtype=object)

In [29]:
x = df.values[:,:-1]  # 독립변수 data

In [30]:
df.values[:,-1]

array([" 'No'", " 'Yes'", "'No' ", " 'No'", " 'Yes'", " 'Yes'", " 'No'",
       " 'Yes'", " 'No'", " 'Yes'"], dtype=object)

In [31]:
y = df.values[:,-1]  # 종속변수, 분류 결과값 (라벨 yes, no)

In [33]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =\
train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
x_train, x_test

# 8:2로 나눔 (test_size = 0.2)

(array([["'France'", '35.0', '58000.0'],
        ["'France'", '44.0', '72000.0'],
        ["'France'", '48.0', '79000.0'],
        ["'Germany'", '30.0', '54000.0'],
        ["'France'", '37.0', '67000.0'],
        ["'Germany'", '40.0', ' nan'],
        ["'Spain'", '38.0', '61000.0'],
        ["'Spain'", ' nan', ' 52000.0']], dtype=object),
 array([["'Germany'", '50.0', '83000.0'],
        ["'Spain'", '27.0', '48000.0']], dtype=object))

In [35]:
y_train, y_test

(array([" 'Yes'", " 'No'", " 'Yes'", "'No' ", " 'Yes'", " 'Yes'", " 'No'",
        " 'No'"], dtype=object),
 array([" 'No'", " 'Yes'"], dtype=object))

In [36]:
x_train.shape, x_test.shape

((8, 3), (2, 3))

In [37]:
x[:,1:3]

array([['44.0', '72000.0'],
       ['27.0', '48000.0'],
       ['30.0', '54000.0'],
       ['38.0', '61000.0'],
       ['40.0', ' nan'],
       ['35.0', '58000.0'],
       [' nan', ' 52000.0'],
       ['48.0', '79000.0'],
       ['50.0', '83000.0'],
       ['37.0', '67000.0']], dtype=object)

In [38]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(strategy='mean')  # nan >> mean 평균값으로 대치 (단순대입법)
imp_mean.fit(x[:,1:3])

# SimpleImputer()로 fitting

SimpleImputer()

In [39]:
imp_mean = imp_mean.fit(x[:,1:3])

In [40]:
x[:,1:3] = imp_mean.transform(x[:,1:3]) # scailing한 값으로 대체

In [41]:
x

array([["'France'", 44.0, 72000.0],
       ["'Spain'", 27.0, 48000.0],
       ["'Germany'", 30.0, 54000.0],
       ["'Spain'", 38.0, 61000.0],
       ["'Germany'", 40.0, 63777.77777777778],
       ["'France'", 35.0, 58000.0],
       ["'Spain'", 38.77777777777778, 52000.0],
       ["'France'", 48.0, 79000.0],
       ["'Germany'", 50.0, 83000.0],
       ["'France'", 37.0, 67000.0]], dtype=object)

In [43]:
df_tf = pd.DataFrame(x[:, 1:3])
df_tf

0             1
0       44.0       72000.0
1       27.0       48000.0
2       30.0       54000.0
3       38.0       61000.0
4       40.0  63777.777778
5       35.0       58000.0
6  38.777778       52000.0
7       48.0       79000.0
8       50.0       83000.0
9       37.0       67000.0

In [44]:
df_tf.describe()

0        1
count   10.0     10.0
unique  10.0     10.0
top     44.0  72000.0
freq     1.0      1.0

---------------

## Feature Scailing

### 1) 표준화 (Standardization)

- 값의 분포를 평균이 0이고, 분산이 1인 가우시안 정규분포를 가진 값으로 변환 -> `standardScaler`
- 경사하강법(서포트 벡터머신이나, 선형회귀, 로지스틱 회귀)에서 데이터가 정규분포를 가지고 있다고 가정
- 하고 구현됐기 떄문에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소
$$
\frac{xi-mean(x)}{stdev(x)}\
\frac{X-\mu}{\sigma}
$$

In [47]:
# 표준화 standardization
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_x.fit_transform(x[:,1:3])
x[:,1:3] = sc_x.transform(x[:,1:3])
x

array([["'France'", 0.758874361590019, 0.7494732544921677],
       ["'Spain'", -1.7115038793306814, -1.4381784072687531],
       ["'Germany'", -1.2755547779917342, -0.8912654918285229],
       ["'Spain'", -0.1130238410878753, -0.253200423814921],
       ["'Germany'", 0.17760889313808945, 6.632191985654332e-16],
       ["'France'", -0.5489729424268225, -0.5266568815350361],
       ["'Spain'", 0.0, -1.0735697969752662],
       ["'France'", 1.3401398300419485, 1.3875383225057696],
       ["'Germany'", 1.6307725642679132, 1.7521469327992565],
       ["'France'", -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

---------------------
연습

In [48]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_x.fit_transform(x[:,1:3])

array([[ 7.58874362e-01,  7.49473254e-01],
       [-1.71150388e+00, -1.43817841e+00],
       [-1.27555478e+00, -8.91265492e-01],
       [-1.13023841e-01, -2.53200424e-01],
       [ 1.77608893e-01,  2.35783334e-16],
       [-5.48972942e-01, -5.26656882e-01],
       [ 1.11022302e-16, -1.07356980e+00],
       [ 1.34013983e+00,  1.38753832e+00],
       [ 1.63077256e+00,  1.75214693e+00],
       [-2.58340208e-01,  2.93712492e-01]])

In [49]:
x[:,1:3] = sc_x.fit_transform(x[:,1:3])
x

array([["'France'", 0.7588743615900191, 0.7494732544921673],
       ["'Spain'", -1.7115038793306812, -1.4381784072687536],
       ["'Germany'", -1.2755547779917342, -0.8912654918285233],
       ["'Spain'", -0.1130238410878752, -0.25320042381492147],
       ["'Germany'", 0.17760889313808956, 2.357833340847479e-16],
       ["'France'", -0.5489729424268224, -0.5266568815350365],
       ["'Spain'", 1.1102230246251565e-16, -1.0735697969752667],
       ["'France'", 1.3401398300419487, 1.3875383225057691],
       ["'Germany'", 1.6307725642679132, 1.752146932799256],
       ["'France'", -0.25834020820085757, 0.2937124916253087]],
      dtype=object)

------------------------

### 2) 정규화 (Normalization)

- 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해 주는 개념 -> `MinMaxScaler`
- 최소 0 ~ 최대 1
- 데이터 분포가 정규 분포가 아닐 경우 적용
-
$
\frac{xi-min(x)}{max(x)-min(x)}
$

In [51]:
# 정규화 min_max 최소-최대

from sklearn.preprocessing import MinMaxScaler

sc_x_minmax = MinMaxScaler()
sc_x_minmax.fit_transform(x[:,1:3])
x[:,1:3] = sc_x_minmax.fit_transform(x[:,1:3])
x

array([["'France'", 0.7391304347826088, 0.6857142857142857],
       ["'Spain'", 0.0, 0.0],
       ["'Germany'", 0.1304347826086956, 0.17142857142857146],
       ["'Spain'", 0.47826086956521746, 0.37142857142857144],
       ["'Germany'", 0.5652173913043479, 0.4507936507936509],
       ["'France'", 0.3478260869565217, 0.28571428571428575],
       ["'Spain'", 0.5120772946859904, 0.11428571428571435],
       ["'France'", 0.9130434782608698, 0.8857142857142858],
       ["'Germany'", 1.0, 1.0],
       ["'France'", 0.4347826086956522, 0.5428571428571428]], dtype=object)

----------------
연습

In [52]:
from sklearn.preprocessing import MinMaxScaler

sc_x_minmax = MinMaxScaler()
sc_x_minmax.fit_transform(x[:,1:3])

array([[0.73913043, 0.68571429],
       [0.        , 0.        ],
       [0.13043478, 0.17142857],
       [0.47826087, 0.37142857],
       [0.56521739, 0.45079365],
       [0.34782609, 0.28571429],
       [0.51207729, 0.11428571],
       [0.91304348, 0.88571429],
       [1.        , 1.        ],
       [0.43478261, 0.54285714]])

In [53]:
x[:,1:3] = sc_x_minmax.fit_transform(x[:,1:3])
x

array([["'France'", 0.7391304347826088, 0.6857142857142857],
       ["'Spain'", 0.0, 0.0],
       ["'Germany'", 0.1304347826086956, 0.17142857142857146],
       ["'Spain'", 0.47826086956521746, 0.37142857142857144],
       ["'Germany'", 0.5652173913043479, 0.4507936507936509],
       ["'France'", 0.3478260869565217, 0.28571428571428575],
       ["'Spain'", 0.5120772946859904, 0.11428571428571435],
       ["'France'", 0.9130434782608698, 0.8857142857142858],
       ["'Germany'", 1.0, 1.0],
       ["'France'", 0.4347826086956522, 0.5428571428571428]], dtype=object)

-------------

## iris 데이터에 적용

In [55]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# iris data loading
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)

print(iris_df)
print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
feature 들의 평균 값
sepal length (cm)    5.8

### iris 표준화(StandardScaler)